### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by j8jacobs** [dberesford/rocksdb-node#10]
Trying to just install rocks db but getting the following error:

In file included from ../rocksdb.cc:3:0:
../DBNode.h:5:24: fatal error: rocksdb/db.h: No such file or directory
 #include "rocksdb/db.h"

using node v9.11.1 on a linux ami instance. Rocksdb is properly configured (i can use the ldb command and can create a db, etc) but not sure why there error is happening. 

The api looks great and would love to use it, looking forward to a response

**Comment by adamjabone** [comment]
Same hear.

**Comment by adamjabone** [comment]
```
 npm install -g rocksdb-node
```
```
> rocksdb-node@1.7.2 install C:\Users\ja1\AppData\Roaming\npm\node_modules\rocksdb-node
> node-gyp rebuild


C:\Users\ja1\AppData\Roaming\npm\node_modules\rocksdb-node>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  rocksdb.cc
  PutWorker.cc
  GetWorker.cc
  DeleteWorker.cc
  OptionsHelper.cc
  Iterator.cc
  Snapshot.cc
  Batch.cc
c:\users\ja1\appdata\roaming\npm\node_modules\rocksdb-node\PutWorker.h(5): fatal error C1083: Cannot open include file:
 'rocksdb/db.h': No such file or directory (compiling source file ..\PutWorker.cc) [C:\Users\ja1\AppData\Roaming\npm\no
de_modules\rocksdb-node\build\rocksdb.vcxproj]
c:\users\ja1\appdata\roaming\npm\node_modules\rocksdb-node\DBNode.h(5): fatal error C1083: Cannot open include file: 'r
ocksdb/db.h': No such file or directory (compiling source file ..\rocksdb.cc) [C:\Users\ja1\AppData\Roaming\npm\node_mo
dules\rocksdb-node\build\rocksdb.vcxproj]
..\Iterator.cc(3): fatal error C1083: Cannot open include file: 'rocksdb/db.h': No such file or directory [C:\Users\ja1
\AppData\Roaming\npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
..\Snapshot.cc(3): fatal error C1083: Cannot open include file: 'rocksdb/db.h': No such file or directory [C:\Users\ja1
\AppData\Roaming\npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
c:\users\ja1\appdata\roaming\npm\node_modules\rocksdb-node\DeleteWorker.h(5): fatal error C1083: Cannot open include fi
le: 'rocksdb/db.h': No such file or directory (compiling source file ..\DeleteWorker.cc) [C:\Users\ja1\AppData\Roaming\
npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
c:\users\ja1\appdata\roaming\npm\node_modules\rocksdb-node\GetWorker.h(5): fatal error C1083: Cannot open include file:
 'rocksdb/db.h': No such file or directory (compiling source file ..\GetWorker.cc) [C:\Users\ja1\AppData\Roaming\npm\no
de_modules\rocksdb-node\build\rocksdb.vcxproj]
..\Batch.cc(3): fatal error C1083: Cannot open include file: 'rocksdb/db.h': No such file or directory [C:\Users\ja1\Ap
pData\Roaming\npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
c:\users\ja1\appdata\roaming\npm\node_modules\rocksdb-node\OptionsHelper.h(5): fatal error C1083: Cannot open include f
ile: 'rocksdb/db.h': No such file or directory (compiling source file ..\OptionsHelper.cc) [C:\Users\ja1\AppData\Roamin
g\npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
  FileWriter.cc
  DBNode.cc
  DBWithTTL.cc
  CompactRangeWorker.cc
  MultiGetWorker.cc
  win_delay_load_hook.cc
c:\users\ja1\appdata\roaming\npm\node_modules\rocksdb-node\MultiGetWorker.h(5): fatal error C1083: Cannot open include
file: 'rocksdb/db.h': No such file or directory (compiling source file ..\MultiGetWorker.cc) [C:\Users\ja1\AppData\Roam
ing\npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
c:\users\ja1\appdata\roaming\npm\node_modules\rocksdb-node\CompactRangeWorker.h(5): fatal error C1083: Cannot open incl
ude file: 'rocksdb/db.h': No such file or directory (compiling source file ..\CompactRangeWorker.cc) [C:\Users\ja1\AppD
ata\Roaming\npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
c:\users\ja1\appdata\roaming\npm\node_modules\rocksdb-node\DBNode.h(5): fatal error C1083: Cannot open include file: 'r
ocksdb/db.h': No such file or directory (compiling source file ..\DBNode.cc) [C:\Users\ja1\AppData\Roaming\npm\node_mod
ules\rocksdb-node\build\rocksdb.vcxproj]
..\DBWithTTL.cc(4): fatal error C1083: Cannot open include file: 'rocksdb/db.h': No such file or directory [C:\Users\ja
1\AppData\Roaming\npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
..\FileWriter.cc(3): fatal error C1083: Cannot open include file: 'rocksdb/db.h': No such file or directory [C:\Users\j
a1\AppData\Roaming\npm\node_modules\rocksdb-node\build\rocksdb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ja1\AppData\Roaming\npm\node_modules\rocksdb-node
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rocksdb-node@1.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rocksdb-node@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ja1\AppData\Roaming\npm-cache\_logs\2018-09-04T10_27_56_848Z-debug.log

```

**Comment by sharonass** [comment]
I cannot install it also,having same problem 
node v8.10.0
npm v3.5.2

**Comment by sharonass** [comment]
Any update About this issue?

**Comment by adamjabone** [comment]
Hi, the project is uncompleted, you need to wait probably up to 3 months
for good debugged version.

śr., 9 sty 2019, 15:23 użytkownik sharonass <notifications@github.com>
napisał:

**Comment by All4nXp** [comment]
Hello, still nothing?

**Comment by dcolley** [comment]
on ubuntu, this seems to work for me
```
sudo apt install python2
nvm install 9
sudo apt install librocksdb-dev
PYTHON=/usr/bin/python2 npm install --save rocksdb-node
```
